### Create a new User
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "walter@email.com",
    "password": "walter123"
}

### find a particular user given an ID
GET http://localhost:3000/auth/1

### Find all users with a given email
GET http://localhost:3000/auth?email=david@email.com

### Delete an user with a given ID
DELETE http://localhost:3000/auth/142352

### Update User
PATCH http://localhost:3000/auth/24644
content-type: application/json

{
    "email": "bbbccc@email.com",
    "password": "bbbccc123"
}